TRAIN:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 16
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_INFLATE: False
  CHECKPOINT_FILE_PATH: "path/to/pretrain.pth"
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_CLEAR_NAME_PATTERN: ("backbone.","encoder.")
DATA:
  PATH_TO_DATA_DIR: "path/to/ava"
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  INPUT_CHANNEL_NUM: [3]
DETECTION:
  ENABLE: True
  ALIGNED: True
AVA:
  FULL_TEST_ON_VAL: True
  MIN_SIZE_TRAIN: [288,]
  MIN_SIZE_TEST: 288
  CROP_ENABLED: False
  IMG_PROC_BACKEND: detectron2
  DETECTION_SCORE_THRESH: 0.7
  TRAIN_PREDICT_BOX_LISTS: []
  TEST_PREDICT_BOX_LISTS: ["ava_val_v2.2.csv"] # Only used for generating coco format json file for person detector head
ViT:
  EMBED_DIM: 768
  DEPTH: 12
  NUM_HEADS: 12
  USE_CHECKPOINT: True
  DROP_PATH_RATE: 0.1
  FPN_INDICES: [ 2, 5, 8, 11 ]
SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  # default 0.000025 for BATCH=16 0.00001 for BATCH=8
  BASE_LR: 0.000025
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 5, 8]
  LRS: [1, 0.1, 0.01]
  LR_SCALE: 8.0
  MAX_EPOCH: 12
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WARMUP_EPOCHS: 2.0
  WARMUP_START_LR: 0.0000025
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 80
  ARCH: vit
  MODEL_NAME: EVAD
  LOSS_FUNC: bce
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  CRD:
    EMBED_DIM: 384
    DEPTH: 6
    NUM_HEADS: 6
    DROP_PATH_RATE: 0.1
TEST:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 4
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
LOG_MODEL_INFO: False
OUTPUT_DIR: "path/to/output/ava_evad_vitb_kpr1"
LOG_PERIOD: 50
TENSORBOARD:
  ENABLE: True
